package db

import (
	"context"

	"github.com/jackc/pgx/v4/pgxpool"
)

const createTaskTableQuery = `CREATE TABLE IF NOT EXISTS tasks (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	
)`

func MigrateTaskTable(ctx context.Context, conn *pgxpool.Pool) error {
	_, err := conn.Exec(ctx, createTaskTableQuery)
	return err
}
